FROM php:7-fpm

COPY ./code /code
COPY ./docker/php.ini /usr/local/etc/php/conf.d/custom.ini
COPY ./docker/cistern.csv /code/var/raspberry/cistern.csv

RUN apt-get update && apt-get install -y git zip unzip && \
    cd /usr/local/bin && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" \
    && cd /code \
    && php /usr/local/bin/composer.phar install \
    && mkdir -p /code/app/cache /code/app/logs /code/web/media/cache /code/var/cache /code/var/logs /code/var/sessions \
    && chmod -R 777 /code/app/cache /code/app/logs /code/web/media/cache /code/var/cache /code/var/logs /code/var/sessions /code/var/raspberry/ \
    && rm -rf /code/app/cache/*