FROM php:7-fpm

COPY ./code /code
COPY ./docker/php.ini /usr/local/etc/php/conf.d/custom.ini
COPY ./docker/cistern.csv /code/var/raspberry/cistern.csv

RUN apt-get update && apt-get install -y git zip unzip && \
    cd /usr/local/bin && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" \
    && cd /code \
    && php /usr/local/bin/composer.phar install \
    && mkdir -p /code/app/cache /code/app/logs /code/web/media/cache /code/var/cache /code/var/logs /code/var/sessions \
    && chmod -R 777 /code/app/cache /code/app/logs /code/web/media/cache /code/var/cache /code/var/logs /code/var/sessions /code/var/raspberry/ \
    && rm -rf /code/app/cache/*